// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrAUDdYy5YqZi_Frr4u5sAgbKubH209JQ',
    appId: '1:601864012611:web:eea1b13af483e66a6465f6',
    messagingSenderId: '601864012611',
    projectId: 'e---commerce-bd176',
    authDomain: 'e---commerce-bd176.firebaseapp.com',
    storageBucket: 'e---commerce-bd176.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJQ1qLy9zk6tl-9X3hpFDaDvAhuKdK6yA',
    appId: '1:601864012611:android:5332e4e847bc8f8a6465f6',
    messagingSenderId: '601864012611',
    projectId: 'e---commerce-bd176',
    storageBucket: 'e---commerce-bd176.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgW86UkwXUyL9gIf5FklQNk8DQa9I0ghQ',
    appId: '1:601864012611:ios:7e9500f09fdfbf916465f6',
    messagingSenderId: '601864012611',
    projectId: 'e---commerce-bd176',
    storageBucket: 'e---commerce-bd176.appspot.com',
    iosBundleId: 'com.example.eCommerse',
  );
}
